css/02-site-header-and-nav.css, style.css
=> remove 3px padding from parent nav li a

css/03-page.css, style.css
- converted the height for `main-header` when it has a `featured-image` from `px` to `vw`
=> feature image height is now dependent on width

css/03-page.css, style.css
- targeted with of section header specifically instead of including column header as well.
- position the bottom breadcrumbs
- changed `box-sizing` for site-footer to `border-box`
=> position bottom breadcrumbs, adjust section headers

parts/after-main.php, style-guide/front.html, style-guide/secondary-featured-img.html, style-guide/secondary.html, style-guide/tertiary.html
A couple things I just noticed (who reviewed this stuff the first time around anyway 😄 ?).
@jeremyfelt @slocker3 #reviewmerge?
=> [PR] Fix typos in the site-wide footer

css/02-site-header-and-nav.css, css/03-page.css, style.css
- 3px added to bottom padding on fourth level nav parent
- remove inner border on featured images
=> Add 3px back for fourth level nav parent

css/04-forms.css, style-guide/gravity-form.html, style.css
This is likely not 100% complete, but it should be more than sufficient for the one form I'm aware of right now.
@jeremyfelt #reviewmerge?
=> [PR] Form style revisions/additions

css/02-site-header-and-nav.css, css/03-page.css, style-guide/front.html, style-guide/gravity-form.html, style-guide/secondary-featured-img.html, style-guide/secondary.html, style-guide/tertiary.html, style.css
- nav and site header should remain the same on desktop no matter what Spine color is selected
- adjusted spacing between columns - halves, margin-right, side-right, thirds
- add padding to global header so content doesn't hit window edge
=> Initial work to overwrite `darker` styles for desktop

css/05-tables.css, functions.php, style-guide/tables.html, style.css
Some quick work...
@jeremyfelt #reviewmerge?
=> [PR] Table styling

css/02-site-header-and-nav.css, style.css
- active states for second level nav parent
- changed font for `#spine` from Lucida to Open Sans
- adjusted font weights
- removed home link for desktop view
=> style active states for main nav, plus other main nav additions

css/02-site-header-and-nav.css, style.css
- cleaned up nav `li` `padding`
- style `active` overview page in nav
=> adjust padding on main nav li

functions.php
Requires https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/pull/353
=> [PR] Filter the section classes added by default

css/03-page.css, style.css
Get `main` content area into the site's standard margins and width
=> Initial layout style for blog, single, and archive

css/02-site-header-and-nav.css, style-guide/tertiary.html, style.css
- initial markup on tertiary styleguide page
- initial styles
=> Initial search/contact bar work

functions.php, parts/headers.php
=> [PR] Update header titles for all views

css/05-tables.css, style.css
Jason and I decided that the previous treatment looked a little too odd on tables with more than two columns.
@slocker3 #reviewmerge?
=> [PR] Change the design for tables

css/01-general-typography.css, css/02-site-header-and-nav.css, css/03-page.css, css/99-video-embeds.css, images/ico-facebook.svg, images/ico-instagram.svg, images/ico-linkedin.svg, images/ico-search-thin.svg, images/ico-twitter.svg, images/ico-youtube.svg, style.css
-align signature with page edge
- incorporated Edit CSS into styles
=> position college sig, and incorporated edit CSS into Git

parts/after-main.php, style-guide/gravity-form.html, style-guide/search-results.html, style-guide/secondary-featured-img.html, style-guide/tables.html
=> [PR] Remove pipes from footer text

css/01-general-typography.css, css/03-page.css, style.css
- eliminated a duplicate `strong` and took `color` off of element
- initial work to make `blockquotes` look better on smaller viewports
- remove border in `site-footer` on smaller viewports
=> general type adjustments

css/01-general-typography.css, style.css
- `blockquote` padding regarding `p` and `cite`
- `blockquote` `cite` resize
=> additional blockquote work for wide screen

single.php
The default Spine single.php had conflicting output for featured images, resulting in a double display.
Fixes #138
=> [PR] Add a custom single.php template

css/01-general-typography.css, css/03-page.css, style.css
- reduce `max-height` on `single-post`
- reduce `margin-top` for `h1`
- adjusted `line-height` and `font-size` for `figcaption`
=> style `single-post`

parts/after-main.php, style-guide/front.html, style-guide/search-results.html, style-guide/secondary-featured-img.html, style-guide/secondary.html, style-guide/tertiary.html
=> [PR] Update alt text for WSU footer logo

css/00-banner.css, functions.php, package.json, style.css
* Introduce a down arrow SVG
* Use the down arrow SVG as a background image for flow charts
* Align bullets to top, remove top spacing from first element in list items
* Update bar graph styles
* Allow for individal items in a list to be animated when in the viewport
* Adjust flow chart styles and timing
* Adjust line height for content in TablePress tables
* Trigger list animation if it is in the viewport on page load
* give video-in-scroll a higher z-index
* Search the medicine.wsu.edu hostname in ES
* Resurface home in horizontal navigation
* Update alt text for WSU footer logo
=> [PR] Bump version 0.1.7

articles/post.php, css/00-banner.css, functions.php, package-lock.json, package.json, parts/headers.php, style.css
We're pretty sure we can get away with all this without disrupting medicine.wsu.edu because they don't seem to be using featured images on any posts there.
=> [PR] Archive structure

functions.php, parts/after-main.php
I made the footer and logo parts of the theme more dynamic so that they can be changed from the customizer tool
=> [PR] Prep for internal nursing news site
